name: Update HelloFresh recipes

on:
  schedule:
    - cron: '0 5 * * 6'
  workflow_dispatch:

jobs:
  update-hellofresh-recipes:
    runs-on: ubuntu-latest
    name: Update HelloFresh recipes
    steps:
      # This step checks out a copy of your repository.
      # Fetch only the root files and listed folders
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            HelloFresh-Weekly
            Recipes2024

      # This step references the directory that contains the action.
      - name: Update HelloFresh recipes and update README.md
        uses: ./
        with:
          file-to-update: README.md

      - name: Commit changes.
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Weekly update"
          git push
        shell: bash
